name: angular_lazy
description: A web app that uses AngularDart Components
version: 1.0.0
author: Suresh

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular2: "^3.0.0"
  angular_components: "^0.5.0"

dev_dependencies:
  browser: ^0.10.0+2
  dart_to_js_script_rewriter: ^1.0.2

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter